/*
 *  Sugar Custom 2018.03.15 - all date methods + array.remove.  note the extend() call at the bottom!
 *
 *  Freely distributable and licensed under the MIT-style license.
 *  Copyright (c)  Andrew Plummer
 *  https://sugarjs.com/
 *
 * ---------------------------- */
(function(){'use strict';function w(a,b){for(var c in a)if(x(a,c)&&!1===b.call(a,a[c],c,a))break}function Xa(a){function b(a,b,c){u(d,a,function(a,e,f){a=Ca(a,e,f);Gb(d,a.methods,b,c,a.v);return d})}var c="Object"===a,d=Ya(a,!0);b("defineStatic",1);b("defineInstance",2);b("defineInstanceAndStatic",3);b("defineStaticWithArguments",1,!0);b("defineInstanceWithArguments",2,!0);u(d,"defineStaticPolyfill",function(b,c,h){b=Ca(b,c,h);qa(Z[a],b.methods,!0,b.v);return d});u(d,"defineInstancePolyfill",function(b,c,h){b=
Ca(b,c,h);qa(Z[a].prototype,b.methods,!0,b.v);w(b.methods,function(a,b){ra(d,b,a)});return d});u(d,"alias",function(a,b){var c=d,e="string"===typeof b?d[b]:b;c[a]=e;e.instance&&ra(c,a,e.instance,!0);return d});u(d,"extend",function(b){function e(a,c){var d=b[a];if(d)for(var e=0,g;g=d[e];e++)if(g===c)return!0;return!1}function h(a,c){return b[a]&&!e(a,c)}function l(a,c,d){if(!c[a]||!d)return!1;for(a=0;a<d.length;a++)if(!1===b[d[a]])return!0}var g=Z[a],p=g.prototype,D={},G={};b=b||{};var q=b.methods;
if(!e("except",g)&&!h("namespaces",g))return c&&"boolean"===typeof b.objectPrototype&&(Da=b.objectPrototype),w(q||d,function(a,b){q&&(b=a,a=d[b]);!x(a,"instance")||c&&p===p&&(!Da||"get"===b||"set"===b)||l(b,p,a.flags)||e("except",b)||(G[b]=a.instance);!x(a,"static")||c&&g===p&&(!Da||"get"===b||"set"===b)||l(b,g,a.flags)||e("except",b)||(D[b]=a)}),qa(g,D),qa(p,G),q||u(d,"active",!0),d});sa[a]=d;$a["[object "+a+"]"]=d;Ea(a);Hb(d);return t[a]=d}function Ib(){return"Sugar"}function Gb(a,b,c,d,e){w(b,
function(b,h){var f=b;d&&(f=ab(b));e&&(f.flags=e);if(c&2&&!b.instance){var g=d?ab(b,!0):Jb(b);u(f,"instance",g)}c&1&&u(f,"static",!0);g=f;a[h]=g;g.instance&&ra(a,h,g.instance,!0);a.active&&a.extend(h)})}function Ca(a,b,c){if("string"===typeof a){var d={};d[a]=b;a=c}else d=a,a=b;return{v:a,methods:d}}function ab(a,b){var c=a.length-1-(b?1:0);return function(){var d=[],e=[];b&&d.push(this);var f=Math.max(arguments.length,c);for(var h=0;h<f;h++)h<c?d.push(arguments[h]):e.push(arguments[h]);d.push(e);
return a.apply(this,d)}}function Jb(a){switch(a.length){case 0:case 1:return function(){return a(this)};case 2:return function(b){return a(this,b)};case 3:return function(b,c){return a(this,b,c)};case 4:return function(b,c,d){return a(this,b,c,d)};case 5:return function(b,c,d,e){return a(this,b,c,d,e)}}}function qa(a,b,c,d){w(b,function(b,f){c&&!d&&a[f]||u(a,f,b)})}function Ya(a){function b(a,d){if(!(this instanceof b))return new b(a,d);this.constructor!==b&&(a=this.constructor.apply(a,arguments));
this.raw=a}u(b,"toString",function(){return"Sugar"+a});u(b.prototype,"valueOf",function(){return this.raw});return b}function ra(a,b,c){c=Kb(c);var d;var e=bb.prototype;var f=(d=e[b])&&d!==Object.prototype[b];d&&d.K||(e[b]=f?Lb(b):c);a.prototype[b]=c;a===t.Object&&Mb(b,c)}function Hb(a){w(t.Object&&t.Object.prototype,function(b,c){if("function"===typeof b){var d=a.prototype;x(d,c)||(d[c]=b)}})}function Mb(a,b){w(sa,function(c){c=c.prototype;x(c,a)||(c[a]=b)})}function Kb(a){return function(){return new bb(a.apply(this.raw,
arguments))}}function Lb(a){function b(){var b=this.raw,d;null!=b&&(d=$a[R(b)]);d||(d=t.Object);return(new d(b))[a].apply(this,arguments)}b.K=!0;return b}function Ea(a,b){var c=sa[a],d=Z[a].prototype;!b&&cb&&(b=cb(d));w(b,function(a){if("constructor"!==a&&"valueOf"!==a&&"__proto__"!==a){try{var b=d[a];if("function"!==typeof b)return}catch(h){return}ra(c,a,b)}})}function Nb(a,b,c){a[b]=c.value}function u(a,b,c,d){Fa(a,b,{value:c,enumerable:!!d,configurable:!0,writable:!0})}function R(a){return Ob.call(a)}
function x(a,b){return!!a&&Pb.call(a,b)}function n(a,b){if(x(a,b))return a[b]}function ta(a,b,c){c||(c=R(a));return c==="[object "+b+"]"}function Ga(a){return function(b,c,d){b[a](c,d)}}function Ha(a,b,c,d){Ia(a,Qb(b,c),d)}function Qb(a,b){var c={};K(a)&&(a=a.split(" "));E(a,function(a,e){b(c,a,e)});return c}function Rb(a,b,c){u(a,b,c)}function m(a){return void 0!==a}function N(a){return void 0===a}function db(a){var b=typeof a;if(null!=a&&"string"!==b&&"number"!==b&&"boolean"!==b){b=R(a);if(eb(a,
b))return Sb(a);if(aa(a,b))return Tb(a);if(ia(a,b))return Ub(a);if(fb(a,b))return Vb(a)}return Wb(a)}function Vb(a){var b={};return function(c,d,e){var f=!0;if(!ja(c))return!1;w(a,function(a,l){b[l]=n(b,l)||db(a);!1===b[l].call(e,c[l],d,e)&&(f=!1);return f});return f}}function Wb(a){return function(b){return ua(b,a)}}function Sb(a){a=RegExp(a);return function(b){return a.test(b)}}function Tb(a){var b=a.getTime();return function(a){return!(!a||!a.getTime)&&a.getTime()===b}}function Ub(a){return function(b,
c,d){return b===a||a.call(d,b,c,d)}}function Ja(a,b){if(x(a,b))return b}function ja(a,b){return!!a&&"object"===(b||typeof a)}function fb(a,b){var c;if(c=ja(a)&&ta(a,"Object",b))c="constructor"in a,c=!c&&!("toString"in a)||c&&!x(a,"constructor")&&x(a.constructor.prototype,"isPrototypeOf");if(c)a:{c=Object.prototype;for(var d in a){var e=a[d];if(!x(a,d)&&e!==c[d]){c=!1;break a}}c=!0}return c}function L(a,b){w(b,function(b,d){a[d]=b});return a}function ua(a,b,c){if(a===b)return 0!==a||1/a===1/b;var d=
R(a);var e=R(b);return d!==e?!1:Ka(a,d)&&Ka(b,e)?Xb(a,b,d,c):La(a,d)&&La(b,e)?a.size===b.size&&ua(gb(a),gb(b),c):Ma(a,d)&&Ma(b,e)?a.size===b.size&&ua(hb(a),hb(b),c):Na(a,d)&&Na(b,e)?a.toString()===b.toString():!1}function Xb(a,b,c,d){if(typeof a!==typeof b)return!1;if(ja(a.valueOf())){if(a.length!==b.length)return!1;var e=0;var f=!0;Yb(a,!1,d,function(a,c,d,p){d||a in b&&ua(c,b[a],p)||(f=!1);e++;return f});if(!f||e!==Object.keys(b).length)return!1}return a.valueOf().toString()===b.valueOf().toString()}
function Yb(a,b,c,d){function e(a,b){var e=!1;if(1<c.length)for(var f=c.length;f--;)c[f]===a&&(e=!0);c.push(a);d(b,a,e,c);c.pop()}function f(){for(var b=Object.keys(a).sort(),c,d=0;d<b.length;d++)c=b[d],e(a[c],b[d])}c||(c=[]);b?f():w(a,e)}function Zb(a,b,c,d){var e=[],f;for(f in a)f>>>0==f&&4294967295!=f&&(c||(d?f<=b:f>=b))&&e.push(+f);e.sort(function(a,c){var d=a>b;return d!==c>b?d?-1:1:a-c});return e}function E(a,b){for(var c=0,d=a.length;c<d;c++){if(!(c in a)){d=a;for(var e=b,f=Zb(d,c,void 0),
h=0,l=f.length;h<l;h++)c=f[h],e.call(d,d[c],c,d);return d}b(a[c],c)}}function $b(a,b){for(var c=[],d=0,e=a.length;d<e;d++){var f=a[d];d in a&&b(f,d)&&c.push(f)}return c}function va(a,b){for(var c=[],d=0,e=a.length;d<e;d++)d in a&&c.push(b(a[d],d));return c}function wa(a,b,c,d,e){d=ba(a).toString(d||10);e=e||"0";b-=d.replace(/\.\d+/,"").length;var f="";for(e=e.toString();0<b;)if(b&1&&(f+=e),b>>=1)e+=e;d=f+d;if(c||0>a)d=(0>a?"-":"+")+d;return d}function ac(a){if(11<=a&&13>=a)return"th";switch(a%10){case 1:return"st";
case 2:return"nd";case 3:return"rd";default:return"th"}}function bc(a,b,c){function d(d,e){var g=e[2],p=e[3],D=e[5];if(e[4]&&b){var l=D;var G=b}else if(g)l=g,G=a;else var r=p&&b?p:e[1]||e[0];if(G){h(c,g,D);var k=function(a,b){return G(a,l,b)}}d.push(k||f(r))}function e(a,b,c,d){if(d>c){var e=b.slice(c,d);l(e,"{");l(e,"}");a.push(function(){return e})}}function f(a){return function(){return a}}function h(a,b,c){if(a&&!a(b,c))throw new TypeError("Invalid token "+(b||c)+" in format string");}function l(a,
b){if(-1!==a.indexOf(b))throw new TypeError("Unmatched "+b+" in format string");}var g=cc,p=dc(function(a){var b=[],c=0,f;for(g.lastIndex=0;f=g.exec(a);)e(b,a,c,f.index),d(b,f),c=g.lastIndex;e(b,a,c,a.length);return b});return function(a,b,c){a=p(a);for(var d="",e=0;e<a.length;e++)d+=a[e](b,c);return d}}function ec(a){K(a)||(a=String(a));return a.replace(/([\\\/'*+?|()\[\]{}.^$-])/g,"\\$1")}function A(a,b){return a["get"+(B(a)?"UTC":"")+b]()}function ca(a,b,c,d){if(!d||c!==A(a,b,c))a["set"+(B(a)?
"UTC":"")+b](c)}function dc(a){var b={},c=0;return function(d){if(x(b,d))return b[d];c===fc&&(b={},c=0);c++;return b[d]=a(d)}}function gb(a){var b=Array(a.size),c=0;a.forEach(function(a){b[c++]=a});return b}function hb(a){var b=Array(a.size),c=0;a.forEach(function(a,e){b[c++]=[e,a]});return b}function W(){return gc("newDateInternal")()}function S(a){var b=new Date(a.getTime());B(b,!!B(a));return b}function ib(a){if(isNaN(a.getTime()))throw new TypeError("Date is not valid");}function y(a){return A(a,
"Day")}function M(a){return A(a,"Date")}function H(a){return A(a,"Month")}function O(a){return A(a,"FullYear")}function P(a,b){ca(a,"Date",b)}function jb(a){return 32-A(new Date(O(a),H(a),32),"Date")}function T(a,b,c){if(Q(b)){var d=y(a);if(c){c=0<c?1:-1;var e=b%7-d;e&&e/ba(e)!==c&&(b+=7*c)}P(a,M(a)+b-d);return a.getTime()}}function Oa(a,b){var c=B(a)?0:a.getTimezoneOffset();var d=!0===b?":":"";if(!c&&b)return"Z";var e=wa(da(-c/60),2,!0);c=wa(ba(c%60),2);return e+d+c}function kb(a,b){var c=a[0],d=
a[1];if(b&&K(c)){var e={};if(c=c.match(/^(-?\d*[\d.]\d*)?\s?(\w+?)s?$/i)){if(N(f)){var f=+c[1];isNaN(f)&&(f=1)}e[c[2].toLowerCase()]=f}c=e}else Q(c)&&Q(d)?(c=hc(a),d=null):ja(c)&&(c=L({},c));return[c,d]}function hc(a){var b={},c=0;lb(7,function(d){var e=a[c++];m(e)&&(b[d.name]=e)});return b}function Pa(a,b,c){c=c||0;for(N(b)&&(b=7);b>=c&&!1!==a(U[b],b);b--);}function lb(a,b){for(;0<=a&&!1!==b(U[a],a);)a=ka(a)}function ka(a){return 6===a?4:5===a?3:a-1}function xa(a,b,c,d){Pa(function(c,d){var e=c.name;
var f=n(a,Qa(a,e));m(f)&&b(e,f,c,d);e=void 0;!1!==e&&4===d&&(e=n(a,Qa(a,"weekday")),m(e)&&b("weekday",e,c,d),e=void 0);return e},c,d)}function ic(a,b){xa(a,b,7,4)}function la(a,b,c,d){var e={};e[b]=c;return V(a,e,d,1)}function mb(a,b,c){b=kb(b,!0);return V(a,b[0],b[1],c)}function ma(a,b){T(a,7*nb((y(a)-b)/7)+b);return a}function ob(a,b){var c=b-1;T(a,7*Ra((y(a)-c)/7)+c);return a}function na(a,b,c){5===b&&ma(a,v.get(c).s());return I(a,ka(b))}function ya(a,b,c,d){5===b&&ob(a,v.get(c).s());return I(a,
ka(b),d,!0)}function I(a,b,c,d){lb(b,function(b,f){var e=d?b.end:b.start;ia(e)&&(e=e(a));ca(a,b.method,e);return!m(c)||f>c});return a}function Qa(a,b){return Ja(a,b)||Ja(a,b+"s")||"day"===b&&Ja(a,"date")}function jc(a){var b={},c;b[a]=1;xa(b,function(a,b,f,h){c=h;return!1});return c}function za(a,b,c){var d=b>a;if(!d){var e=b;b=a;a=e}e=b-a;1<c.h&&(e=da(e/c.h));if(c.m)for(a=S(a),e&&la(a,c.name,e);a<b;){la(a,c.name,1);if(a>b)break;e+=1}return d?-e:e}function pb(a,b){if(Q(b)){var c=S(a),d=y(a);I(c,6);
P(c,4);ma(c,1);P(c,M(c)+7*(b-1));var e=O(c);ca(a,"FullYear",e);e=H(c);ca(a,"Month",e);P(a,M(c));T(a,d||7)}return a.getTime()}function ea(a,b,c,d){var e,f=0;N(c)&&(c=1);N(d)&&(d=4);var h=e=ob(S(a),c),l=c,g=d;I(h,6);P(h,g);ma(h,l);b&&a<e&&(b=e=ma(S(a),c),I(b,6),P(b,d),ma(b,c));for(;e<=a;)P(e,M(e)+7),f++;return f}function qb(a,b,c){var d=O(a);var e=H(a);if(0===e||11===e){if(!c){c=v.get(b);var f=c.s(b);var h=c.D(b)}a=ea(a,!1,f,h);0===e&&0===a?--d:11===e&&1===a&&(d+=1)}return d}function rb(a,b,c,d){var e;
ib(a);ia(c)?d=c:e=c;c=kc(a,b);if(d&&(d=d.apply(a,c.concat(v.get(e)))))return sb(a,d,e);0===c[1]&&(c[1]=1,c[0]=1);a=b?"duration":0<c[2]?"future":"past";return v.get(e).P(c,a)}function lc(a,b){var c=0,d=0;Pa(function(a,f){d=ba(b(a));if(1<=d)return c=f,!1});return[d,c,a]}function kc(a,b){b||(b=W(),a>b&&(b=new Date(b.getTime()-10)));return lc(a-b,function(c){return ba(za(a,b,c))})}function sb(a,b,c){ib(a);b=tb[b]||b||"{long}";return Aa(b,a,c)}function Sa(a,b){var c=A(a,"Hours");return v.get(b).ampm[da(c/
12)]||""}function ub(a,b,c){var d;if(!isNaN(a.getTime())){if(K(b))switch(b=b.trim().toLowerCase(),!0){case "future"===b:return a.getTime()>W().getTime();case "past"===b:return a.getTime()<W().getTime();case "today"===b:return Ta(a);case "tomorrow"===b:return Ta(a,1);case "yesterday"===b:return Ta(a,-1);case "weekday"===b:return 0<y(a)&&6>y(a);case "weekend"===b:return 0===y(a)||6===y(a);case m(d=X.weekdayMap[b]):return y(a)===d;case m(d=X.monthMap[b]):return H(a)===d}return vb(a,b,c)}}function vb(a,
b,c,d,e){var f=0,h=0;B(a)&&(e=e||{},e.fromUTC=!0,e.setUTC=!0);b=oa(null,b,e,!0);if(0<c){f=h=c;var l=!0}if(isNaN(b.date.getTime()))return!1;if(b.set&&b.set.specificity){if(m(b.set.edge)||m(b.set.shift)){var g=!0;na(b.date,b.set.specificity,d)}if(g||6===b.set.specificity)var p=ya(S(b.date),b.set.specificity,d).getTime();else p=U[b.set.specificity],p=la(S(b.date),p.name,1).getTime()-1;!l&&m(b.set.sign)&&b.set.specificity&&(f=50,h=-50)}c=a.getTime();l=b.date.getTime();p=p||l;if(a=b.set&&b.set.specificity?
0:6E4*(b.date.getTimezoneOffset()-a.getTimezoneOffset()))l-=a,p-=a;return c>=l-f&&c<=p+h}function Ta(a,b){var c=W();b&&P(c,M(c)+b);return O(a)===O(c)&&H(a)===H(c)&&M(a)===M(c)}function Y(a,b,c){return oa(null,a,b,c).date}function oa(a,b,c,d){function e(a,b){var c=n(z,"params")||{};E(b.to,function(b,d){var e=a[d+1];if(e){if("yy"===b||"y"===b){b="year";var g=n(z,"prefer");e=+e;e+=50>e?2E3:1900;if(g){var f=e-O(r);f/ba(f)!==g&&(e+=100*g)}}else(g=n(Ua,b))?(b=g.g||b,f=g.B?g.B:g.sign?"+"===e?1:-1:g.U?!!f:
+e.replace(/,/,"."),"month"===g.g&&--f,e=f):e=q.R(b,e);c[b]=e}});return c}function f(a,b){B(a)&&!m(n(z,"fromUTC"))&&(z.fromUTC=!0);B(a)&&!m(n(z,"setUTC"))&&(z.setUTC=!0);b&&(a=new Date(a.getTime()));return a}function h(){E(u,function(a){a.call()})}function l(a){a=a.toLowerCase();q=v.get(n(z,"locale"));for(var b=0,c,d;c=q.compiledFormats[b];b++)if(d=a.match(c.reg)){q.I(c,b);k=e(d,c);if(m(k.timestamp)){a=k.timestamp;k=null;break}m(k.ampm)&&(b=k.ampm,1===b&&12>k.hour?k.hour+=12:0===b&&12===k.hour&&(k.hour=
0));if(k.utc||m(k.tzHour))if(b=k.tzHour,c=k.tzMinute,d=k.tzSign,B(r,!0),b=(d||1)*(60*(b||0)+(c||0)))k.minute=(k.minute||0)-b;m(k.shift)&&N(k.unit)&&(m(k.month)?k.unit=7:m(k.weekday)&&(k.unit=5));m(k.num)&&N(k.unit)&&(m(k.weekday)?D(k.num):m(k.month)&&(k.date=k.num));k.midday&&g(k.midday);m(k.day)&&(I(r,3),N(k.unit)&&(k.unit=4,k.num=k.day,delete k.day));m(k.unit)&&(b=k.unit,c=m(k.num)?k.num:1,m(k.weekday)&&(6===b?(D(c),c=1):(V(r,{weekday:k.weekday},!0),delete k.weekday)),k.half&&(c*=k.half),m(k.shift)?
c*=k.shift:k.sign&&(c*=k.sign),m(k.day)&&(c+=k.day,delete k.day),G(b),k[X.units[b]]=c,Za=!0);k.edge&&p(k.edge,k);k.yearSign&&(k.year*=k.yearSign);break}k?Za?V(r,k,!1,1):(B(r)&&I(r,3),V(r,k,!0,0,n(z,"prefer"),t)):(r=new Date(a),n(z,"fromUTC")&&r.setTime(r.getTime()+6E4*r.getTimezoneOffset()));h();return r}function g(a){k.hour=a%24;23<a&&u.push(function(){la(r,"date",da(a/24))})}function p(a,b){var c=b.unit;c||ic(b,function(a,d,e,g){"weekday"===a&&m(b.month)||(c=g)});if(6===c&&m(b.weekday)){var d=b.weekday;
delete b.weekday}u.push(function(){if(0>a)na(r,c,n(z,"locale"));else if(0<a){if(1===a){var b=4;na(r,4)}ya(r,c,n(z,"locale"),b)}m(d)&&(T(r,d,-a),I(r,3))});b.specificity=6===c?4:c-1}function D(a){k.weekday=7*(a-1)+k.weekday;t=k.date=1}function G(a){var b;xa(k,function(c,d,e,g){if(g>=a)return r.setTime(NaN),!1;g<a&&(b=b||{},b[c]=d,delete k[Qa(k,c)])});b&&(u.push(function(){V(r,b,!0,!1,n(z,"prefer"),t)}),k.edge&&(p(k.edge,b),delete k.edge))}var q,Za,t;var u=[];var z=function(a){a=K(a)?{locale:a}:a||{};
a.prefer=+!!n(a,"future")-+!!n(a,"past");return a}(c);var r=a&&b?f(a,!0):W();B(r,n(z,"fromUTC"));if(K(b))r=l(b);else if(aa(b))r=f(b,x(z,"clone")||d);else if(ja(b)){var k=L({},b);V(r,k,!0)}else(Q(b)||null===b)&&r.setTime(b);B(r,!!n(z,"setUTC"));return{set:k,date:r}}function V(a,b,c,d,e,f){function h(){var a=U[g];d=e;l(a.name,1,a,g)}function l(c,h,l,q){var p=l.method,D;e&&!g&&(g="weekday"===c?5:4===q?6:q+1);q>b.specificity||(b.specificity=q);if(D=h%1){if(q){var G=U[ka(q)];D=mc(l.h/G.h*D);b[G.name]=
D}h=da(h)}if("weekday"===c)d||T(a,h,f);else if(c=6===q&&28<M(a),d&&!l.m)a.setTime(a.getTime()+h*d*l.h);else{d&&(5===q&&(h*=7,p=U[4].method),h=h*d+A(a,p));l=p;q=h;p=d;"ISOWeek"===l?pb(a,q):ca(a,l,q,p);if(l=c)0>h&&(h=h%12+12),l=h%12!==H(a);l&&P(a,0)}}var g;if(Q(b)&&d)b={millisecond:b};else if(Q(b))return a.setTime(b),a;xa(b,l);c&&b.specificity&&I(a,ka(b.specificity));a:{if(g&&!(7<g))switch(e){case -1:c=a>W();break a;case 1:c=a<W();break a}c=void 0}c&&h();return a}function Ba(a){var b=a.join("");return a&&
a.length?b.length===a.length?"["+b+"]":va(a,ec).join("|"):""}function J(a,b){1<a.length&&(a="(?:"+a+")");b&&(a+="?");return a}function nc(a,b,c){a=wb[a];return b=a.w?J(b+J(c)):a.H?b+J(a.H+"|"+c):b+J(c,!0)}function xb(a,b,c,d){var e;1<c&&(e=a[b+(c-1)*d]);return e||a[b]}function yb(a){function b(a){this.S(a)}b.prototype={F:function(a,b){return this.monthSuffix?a+1+this.monthSuffix:xb(this.months,a,b,12)},G:function(a,b){return xb(this.weekdays,a,b,7)},R:function(a,b){var c=this[a+"Map"],d;c&&(d=c[b]);
N(d)&&(d=this.M(b),"month"===a&&--d);return d},M:function(a){var b=this.numeralMap[a];if(m(b))return b;b=+a.replace(/,/,".");if(!isNaN(b))return b;b=this.N(a);isNaN(b)||(this.numeralMap[a]=b);return b},N:function(a){var b=1,c=0,f;var h=a.split("");for(var l=h.length-1;f=h[l];l--){a=n(this.numeralMap,f);N(a)&&(a=n(fa,f)||0);(f=0<a&&0===a%10)?(g&&(c+=b),l?b=a:c+=a):(c+=a*b,b*=10);var g=f}return c},O:function(a){return this.ordinalSuffix||ac(a)},P:function(a,b){return this.J(a,b)},s:function(){var a=
this.firstDayOfWeek;return m(a)?a:1},D:function(){return this.firstDayOfWeekYear||4},J:function(a,b){var c=a[0],d=a[1],h=a[2],l=this[b]||this.relative;if(ia(l))return l.call(this,c,d,h,b);var g=this.units[8*(this.plural&&1!==c?1:0)+d]||this.units[d];var p=this[0<h?"fromNow":"ago"];return l.replace(/\{(.*?)\}/g,function(a,b){switch(b){case "num":return c;case "unit":return g;case "sign":return p}})},I:function(a,b){this.compiledFormats.splice(b,1);this.compiledFormats.unshift(a)},addFormat:function(a,
b){function c(a){var c,e=a.match(/\?$/),f=a.match(/^(\d+)\??$/),l=a.match(/(\d)(?:-(\d))?/),q=a.replace(/[^a-z]+$/i,"");if(c=n(h.parsingAliases,q))return a=d(c),e&&(a=J(a,!0)),a;if(f)a=h.tokens[f[1]];else if(c=n(Ua,q))a=c.src;else if(c=n(h.parsingTokens,q)||n(h,q),q=q.replace(/s$/,""),c||(c=n(h.parsingTokens,q)||n(h,q+"s")),K(c)){a=c;var m=h[q+"Suffix"]}else l&&(c=$b(c,function(a,b){var d=b%(h.units?8:c.length);return d>=l[1]&&d<=(l[2]||l[1])})),a=Ba(c);if(!a)return"";f?a=J(a):(b.push(q),a="("+a+
")");m&&(a=nc(q,a,m));e&&(a+="?");return a}function d(a){a=a.replace(/ /g," ?");return a.replace(/\{([^,]+?)\}/g,function(a,b){var d=b.split("|");return 1<d.length?J(va(d,c).join("|")):c(b)})}var h=this;b||(b=[],a=d(a));h.addRawFormat(a,b)},addRawFormat:function(a,b){this.compiledFormats.unshift({reg:RegExp("^ *"+a+" *$","i"),to:b})},S:function(a){function b(a,b,d,e){var f=a,h=[];g[f]||(f+="s");if(!d){d={};var p=!0}c(f,function(a,c,f){c=c*b+f;f=e?e(f):f;d[a]=f;d[a.toLowerCase()]=f;h[c]=a});g[f]=h;
p&&(g[a+"Map"]=d)}function c(a,b){E(g[a],function(a,c){f(a,function(a,d){b(a,d,c)})})}function f(a,b){var c=va(a.split("+"),function(a){return a.replace(/(.+):(.+)$/,function(a,b,c){return va(c.split("|"),function(a){return b+a}).join("|")})}).join("|");E(c.split("|"),b)}function h(a,b,c){E(g[a],function(a){b&&(a=c?J("{time}[,\\s\\u3000]",!0)+a:a+l());g.addFormat(a)})}function l(){var a=",?[\\s\\u3000]",b;(b=Ba(g.timeMarkers))&&(a+="| (?:"+b+") ");a=J(a,g.timeMarkerOptional);return J(a+"{time}",!0)}
var g=this;g.compiledFormats=[];g.parsingAliases={};g.parsingTokens={};L(g,a);(function(){E(oc,function(a){var b=g[a];K(b)?g[a]=b.split(","):b||(g[a]=[])})})();b("month",12);b("weekday",7);b("unit",8);b("ampm",2);(function(){var a={};b("numeral",10,a);b("article",1,a,function(){return 1});b("placeholder",4,a,function(a){return pc(10,a+1)});g.numeralMap=a})();g.parsingAliases.time=g.ampmFront?"{ampm?} {hour} (?:{minute} (?::?{second})?)?":g.ampm.length?"{hour}(?:[.:]{minute}(?:[.:]{second})? {ampm?}| {ampm})":
"{hour}(?:[.:]{minute}(?:[.:]{second})?)";g.parsingAliases.tzOffset="(?:{Z}|{GMT?}(?:{tzSign}{tzHour}(?::?{tzMinute}(?: \\([\\w\\s]+\\))?)?)?)?";(function(){w(wb,function(a,b){var c=a.j?Ua[a.j].src:a.src;if(a.T||g.numeralUnits){var d="";var e=g.numerals.concat(g.placeholders).concat(g.articles);g.allowsFullWidth&&(e=e.concat(zb.split("")));e.length&&(d="|(?:"+Ba(e)+")+");c+=d}(e=g[b+"s"])&&e.length&&(c+="|"+Ba(e));g.parsingTokens[b]=c})})();(function(){Pa(function(a,b){var c=g.timeSuffixes[b];c&&
(g[(a.alias||a.name)+"Suffix"]=c)})})();(function(){E(g.modifiers,function(a){var b=a.name,c=b+"Map";var d=g[c]||{};f(a.src,function(c,e){var f=n(g.parsingTokens,b),h=a.value;d[c]=h;g.parsingTokens[b]=f?f+"|"+c:c;"sign"===a.name&&0===e&&(g[1===h?"fromNow":"ago"]=c)});g[c]=d})})();(function(){E(qc,function(a){var b=a.src;a.mdy&&g.mdy&&(b=a.mdy);a.time?(g.addFormat(J("{time}[,\\s\\u3000]",!0)+b),g.addFormat(b+l())):g.addFormat(b)});g.addFormat("{time}")})();h("parse");h("timeParse",!0);h("timeFrontParse",
!0,!0)}};return new b(a)}function Va(a,b){this.start=Ab(a);this.end=Ab(b)}function Ab(a){return aa(a)?new Date(a.getTime()):null==a?a:aa(a)?a.getTime():a.valueOf()}function ha(a){return aa(a)?a:null==a?new Date:F.create?F.create(a):new Date(a)}var t,Z="undefined"!==typeof global&&global.Object===Object?global:this,rc="undefined"!==typeof module&&module.L,Da=!1,sa={},$a={},Fa=Object.defineProperty&&Object.defineProperties?Object.defineProperty:Nb,bb=Ya("Chainable"),cb=Object.getOwnPropertyNames,Ob=
Object.prototype.toString,Pb=Object.prototype.hasOwnProperty;(function(){t=Z.Sugar;if(!t){t=function(a){w(t,function(b,c){x(sa,c)&&b.extend(a)});return t};if(rc)module.L=t;else try{Z.Sugar=t}catch(a){}w("Object Number String Array Date RegExp Function".split(" "),function(a){Xa(a)});u(t,"extend",t);u(t,"toString",Ib);u(t,"createNamespace",Xa);u(t,"util",{hasOwn:x,getOwn:n,setProperty:u,classToString:R,defineProperty:Fa,forEachProperty:w,mapNativeToChainable:Ea})}})();var cc=/([{}])\1|\{([^}]*)\}|(%)%|(%(\w*))/g,
sc=t.Array,F=t.Date;x=t.util.hasOwn;n=t.util.getOwn;u=t.util.setProperty;R=t.util.classToString;Fa=t.util.defineProperty;w=t.util.forEachProperty;Ea=t.util.mapNativeToChainable;var Ka,Q,K,aa,eb,ia,La,Ma,Na,Bb=Ga("defineStatic"),Ia=Ga("defineInstance"),tc=Ga("defineInstanceWithArguments"),da=Math.trunc||function(a){return 0!==a&&isFinite(a)?0>a?Ra(a):nb(a):a},fa,zb,ba=Math.abs,pc=Math.pow,uc=Math.min,vc=Math.max,Ra=Math.ceil,nb=Math.floor,mc=Math.round,Cb=String.fromCharCode,B=function(a){var b="_sugar_"+
a;return function(a,d){return 1<arguments.length?(u(a,b,d),a):a[b]}}("utc"),fc=1E3;(function(){function a(a){f["[object "+a+"]"]=!0}function b(a,b){return b&&ta(new b,"Object")?c(b):d(a)}function c(a){var b=String(a);return function(a){return String(a.constructor)===b}}function d(a){return function(b,c){return ta(b,a,c)}}function e(a){var b=a.toLowerCase();return function(c){var d=typeof c;return d===b||"object"===d&&ta(c,a)}}var f={};(function(){var c="Boolean Number String Date RegExp Function Array Error Set Map".split(" ");
Q=e(c[1]);K=e(c[2]);aa=b(c[3]);eb=b(c[4]);ia=b(c[5]);Array.isArray||b(c[6]);Na=b(c[7]);La=b(c[8],"undefined"!==typeof Set&&Set);Ma=b(c[9],"undefined"!==typeof Map&&Map);a("Arguments");a(c[0]);a(c[1]);a(c[2]);a(c[3]);a(c[4]);a(c[6])})();(function(){E("Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64".split(" "),function(b){a(b+"Array")})})();Ka=function(a,b){b=b||R(a);return f[b]||fb(a,b)}})();(function(){var a="";fa={};for(var b=0,c;9>=b;b++)c=Cb(b+65296),a+=c,fa[c]=Cb(b+48);fa[","]=
"";fa["\uff0e"]=".";fa["."]=".";zb=a})();var oc="months weekdays units numerals placeholders articles tokens timeMarkers ampm timeSuffixes parse timeParse timeFrontParse modifiers".split(" "),wc=/(\w{3})[()\s\d]*$/,Ua={yyyy:{g:"year",src:"\\d{4}"},MM:{g:"month",src:"[01]?\\d"},dd:{g:"date",src:"[0123]?\\d"},hh:{g:"hour",src:"[0-2]?\\d"},mm:{g:"minute",src:"[0-5]\\d"},ss:{g:"second",src:"[0-5]\\d(?:[,.]\\d+)?"},yy:{g:"year",src:"\\d{2}"},y:{g:"year",src:"\\d"},yearSign:{src:"[+-]",sign:!0},tzHour:{src:"[0-1]\\d"},
tzMinute:{src:"[0-5]\\d"},tzSign:{src:"[+\u2212-]",sign:!0},ihh:{g:"hour",src:"[0-2]?\\d(?:[,.]\\d+)?"},imm:{g:"minute",src:"[0-5]\\d(?:[,.]\\d+)?"},GMT:{g:"utc",src:"GMT",B:1},Z:{g:"utc",src:"Z",B:1},timestamp:{src:"\\d+"}},wb={year:{j:"yyyy",w:!0},month:{j:"MM",w:!0},date:{j:"dd",w:!0},hour:{j:"hh",H:":"},minute:{j:"mm"},second:{j:"ss"},num:{src:"\\d+",T:!0}},qc=[{src:"{MM}[-.\\/]{yyyy}"},{time:!0,src:"{dd}[-.\\/]{MM}(?:[-.\\/]{yyyy|yy|y})?",mdy:"{MM}[-.\\/]{dd}(?:[-.\\/]{yyyy|yy|y})?"},{time:!0,
src:"{yyyy}[-.\\/]{MM}(?:[-.\\/]{dd})?"},{src:"\\\\/Date\\({timestamp}(?:[+-]\\d{4,4})?\\)\\\\/"},{src:"{yearSign?}{yyyy}(?:-?{MM}(?:-?{dd}(?:T{ihh}(?::?{imm}(?::?{ss})?)?)?)?)?{tzOffset?}"}],tb={ISO8601:"{yyyy}-{MM}-{dd}T{HH}:{mm}:{ss}.{SSS}{Z}",RFC1123:"{Dow}, {dd} {Mon} {yyyy} {HH}:{mm}:{ss} {ZZ}",RFC1036:"{Weekday}, {dd}-{Mon}-{yy} {HH}:{mm}:{ss} {ZZ}"},xc=[{b:"Dow",a:"a",i:"dow",get:function(a,b){return v.get(b).G(y(a),2)}},{b:"Weekday",a:"A",i:"weekday",C:!0,get:function(a,b,c){return v.get(b).G(y(a),
c)}},{b:"Mon",a:"b h",i:"mon",get:function(a,b){return v.get(b).F(H(a),2)}},{b:"Month",a:"B",i:"month",C:!0,get:function(a,b,c){return v.get(b).F(H(a),c)}},{a:"C",get:function(a){return O(a).toString().slice(0,2)}},{b:"d date day",a:"d",f:2,c:"dd",l:"do",get:function(a){return M(a)}},{a:"e",get:function(a){return wa(M(a),2,!1,10," ")}},{b:"H 24hr",a:"H",f:2,c:"HH",get:function(a){return A(a,"Hours")}},{b:"h hours 12hr",a:"I",f:2,c:"hh",get:function(a){return A(a,"Hours")%12||12}},{b:"D",a:"j",f:3,
c:"DDD",get:function(a){var b=I(S(a),6);return za(a,b,U[4])+1}},{b:"M",a:"m",f:2,l:"Mo",c:"MM",get:function(a){return H(a)+1}},{b:"m minutes",a:"M",f:2,c:"mm",get:function(a){return A(a,"Minutes")}},{b:"Q",get:function(a){return Ra((H(a)+1)/3)}},{b:"TT",a:"p",get:function(a,b){return Sa(a,b)}},{b:"tt",a:"P",get:function(a,b){return Sa(a,b).toLowerCase()}},{b:"T",i:"t",get:function(a,b){return Sa(a,b).charAt(0)}},{b:"s seconds",a:"S",f:2,c:"ss",get:function(a){return A(a,"Seconds")}},{b:"S ms",f:3,
c:"SSS",get:function(a){return A(a,"Milliseconds")}},{b:"e",a:"u",l:"eo",get:function(a){return y(a)||7}},{a:"U",f:2,get:function(a){return ea(a,!1,0)}},{b:"W",a:"V",f:2,l:"Wo",c:"WW",get:function(a){return ea(a,!0)}},{a:"w",get:function(a){return y(a)}},{b:"w",l:"wo",c:"ww",get:function(a,b){var c=v.get(b);return ea(a,!0,c.s(b),c.D(b))}},{a:"W",f:2,get:function(a){return ea(a,!1)}},{c:"gggg",u:"gg",get:function(a,b){return qb(a,b)}},{a:"G",f:4,A:"g",c:"GGGG",u:"GG",get:function(a,b){return qb(a,
b,!0)}},{b:"year",c:"yyyy",u:"yy",a:"Y",f:4,A:"y",get:function(a){return O(a)}},{b:"ZZ",a:"z",get:function(a){return Oa(a)}},{b:"X",get:function(a){return da(a.getTime()/1E3)}},{b:"x",get:function(a){return a.getTime()}},{b:"Z",get:function(a){return Oa(a,!0)}},{b:"z",a:"Z",get:function(a){return(a=a.toString().match(wc))?a[1]:""}},{a:"D",alias:"%m/%d/%y"},{a:"F",alias:"%Y-%m-%d"},{a:"r",alias:"%I:%M:%S %p"},{a:"R",alias:"%H:%M"},{a:"T",alias:"%H:%M:%S"},{a:"x",alias:"{short}"},{a:"X",alias:"{time}"},
{a:"c",alias:"{stamp}"}],U=[{name:"millisecond",method:"Milliseconds",h:1,start:0,end:999},{name:"second",method:"Seconds",h:1E3,start:0,end:59},{name:"minute",method:"Minutes",h:6E4,start:0,end:59},{name:"hour",method:"Hours",h:36E5,start:0,end:23},{name:"day",alias:"date",method:"Date",m:!0,h:864E5,start:1,end:function(a){return jb(a)}},{name:"week",method:"ISOWeek",m:!0,h:6048E5},{name:"month",method:"Month",m:!0,h:26298E5,start:0,end:11},{name:"year",method:"FullYear",m:!0,h:315576E5,start:0}],
gc=function(a,b){function c(a){return d[a]}var d=L({},b);u(a,"getOption",c);Rb(a,"setOption",function(a,c){if(1===arguments.length)var e=a;else e={},e[a]=c;w(e,function(a,c){null===a&&(a=b[c]);d[c]=a})});return c}(F,{newDateInternal:function(){return new Date}}),C,pa,Aa,X,v;Bb(F,{create:function(a,b){return Y(a,b)},getLocale:function(a){return v.get(a,!a)},getAllLocales:function(){return v.getAll()},getAllLocaleCodes:function(){return Object.keys(v.getAll())},setLocale:function(a){return v.set(a)},
addLocale:function(a,b){return v.add(a,b)},removeLocale:function(a){return v.remove(a)}});tc(F,{set:function(a,b){b=kb(b);return V(a,b[0],b[1])},advance:function(a,b){return mb(a,b,1)},rewind:function(a,b){return mb(a,b,-1)}});Ia(F,{get:function(a,b,c){return oa(a,b,c,void 0).date},setWeekday:function(a,b){return T(a,b)},setISOWeek:function(a,b){return pb(a,b)},getISOWeek:function(a){return ea(a,!0)},beginningOfISOWeek:function(a){var b=y(a);0===b?b=-6:1!==b&&(b=1);T(a,b);return I(a,3)},endOfISOWeek:function(a){0!==
y(a)&&T(a,7);return ya(a,4)},getUTCOffset:function(a,b){return Oa(a,b)},setUTC:function(a,b){return B(a,b)},isUTC:function(a){return!!B(a)||0===a.getTimezoneOffset()},isValid:function(a){return!isNaN(a.getTime())},isAfter:function(a,b,c){return a.getTime()>Y(b).getTime()-(c||0)},isBefore:function(a,b,c){return a.getTime()<Y(b).getTime()+(c||0)},isBetween:function(a,b,c,d){a=a.getTime();b=Y(b).getTime();var e=Y(c).getTime();c=uc(b,e);b=vc(b,e);d=d||0;return c-d<=a&&b+d>=a},isLeapYear:function(a){a=
O(a);return 0===a%4&&0!==a%100||0===a%400},daysInMonth:function(a){return jb(a)},format:function(a,b,c){return sb(a,b,c)},relative:function(a,b,c){return rb(a,null,b,c)},relativeTo:function(a,b,c){return rb(a,Y(b),c)},is:function(a,b,c){return ub(a,b,c)},reset:function(a,b,c){b=b?jc(b):4;na(a,b,c);return a},clone:function(a){return S(a)},iso:function(a){return a.toISOString()},getWeekday:function(a){return y(a)},getUTCWeekday:function(a){return a.getUTCDay()}});var Wa={code:"en",plural:!0,timeMarkers:"at",
ampm:"AM|A.M.|a,PM|P.M.|p",units:"millisecond:|s,second:|s,minute:|s,hour:|s,day:|s,week:|s,month:|s,year:|s",months:"Jan:uary|,Feb:ruary|,Mar:ch|,Apr:il|,May,Jun:e|,Jul:y|,Aug:ust|,Sep:tember|t|,Oct:ober|,Nov:ember|,Dec:ember|",weekdays:"Sun:day|,Mon:day|,Tue:sday|,Wed:nesday|,Thu:rsday|,Fri:day|,Sat:urday|+weekend",numerals:"zero,one|first,two|second,three|third,four:|th,five|fifth,six:|th,seven:|th,eight:|h,nin:e|th,ten:|th",articles:"a,an,the",tokens:"the,st|nd|rd|th,of|in,a|an,on",time:"{H}:{mm}",
past:"{num} {unit} {sign}",future:"{num} {unit} {sign}",duration:"{num} {unit}",modifiers:[{name:"half",src:"half",value:.5},{name:"midday",src:"noon",value:12},{name:"midday",src:"midnight",value:24},{name:"day",src:"yesterday",value:-1},{name:"day",src:"today|tonight",value:0},{name:"day",src:"tomorrow",value:1},{name:"sign",src:"ago|before",value:-1},{name:"sign",src:"from now|after|from|in|later",value:1},{name:"edge",src:"first day|first|beginning",value:-2},{name:"edge",src:"last day",value:1},
{name:"edge",src:"end|last",value:2},{name:"shift",src:"last",value:-1},{name:"shift",src:"the|this",value:0},{name:"shift",src:"next",value:1}],parse:"(?:just)? now;{shift} {unit:5-7};{months?} (?:{year}|'{yy});{midday} {4?} {day|weekday};{months},?(?:[-.\\/\\s]{year})?;{edge} of (?:day)? {day|weekday};{0} {num}{1?} {weekday} {2} {months},? {year?};{shift?} {day?} {weekday?} {timeMarker?} {midday};{sign?} {3?} {half} {3?} {unit:3-4|unit:7} {sign?};{0?} {edge} {weekday?} {2} {shift?} {unit:4-7?} {months?},? {year?}".split(";"),
timeParse:"{day|weekday};{shift} {unit:5?} {weekday};{0?} {date}{1?} {2?} {months?};{weekday} {2?} {shift} {unit:5};{0?} {num} {2?} {months}\\.?,? {year?};{num?} {unit:4-5} {sign} {day|weekday};{year}[-.\\/\\s]{months}[-.\\/\\s]{date};{0|months} {date?}{1?} of {shift} {unit:6-7};{0?} {num}{1?} {weekday} of {shift} {unit:6};{date}[-.\\/\\s]{months}[-.\\/\\s](?:{year}|'?{yy});{weekday?}\\.?,? {months}\\.?,? {date}{1?},? (?:{year}|'{yy})?".split(";"),timeFrontParse:["{sign} {num} {unit}","{num} {unit} {sign}",
"{4?} {day|weekday}"]},Db=L(L({},Wa),{mdy:!0,firstDayOfWeek:0,firstDayOfWeekYear:1,"short":"{MM}/{dd}/{yyyy}",medium:"{Month} {d}, {yyyy}","long":"{Month} {d}, {yyyy} {time}",full:"{Weekday}, {Month} {d}, {yyyy} {time}",stamp:"{Dow} {Mon} {d} {yyyy} {time}",time:"{h}:{mm} {TT}"}),Eb=L(L({},Wa),{"short":"{dd}/{MM}/{yyyy}",medium:"{d} {Month} {yyyy}","long":"{d} {Month} {yyyy} {H}:{mm}",full:"{Weekday}, {d} {Month}, {yyyy} {time}",stamp:"{Dow} {d} {Mon} {yyyy} {time}"}),yc=L(L({},Wa),{"short":"{yyyy}-{MM}-{dd}",
medium:"{d} {Month}, {yyyy}","long":"{d} {Month}, {yyyy} {H}:{mm}",full:"{Weekday}, {d} {Month}, {yyyy} {time}",stamp:"{Dow} {d} {Mon} {yyyy} {time}"}),Fb={"en-US":Db,"en-GB":Eb,"en-AU":Eb,"en-CA":yc};(function(){function a(a){this.o={};this.add(a)}a.prototype={get:function(a,c){var b=this.o[a];!b&&Fb[a]?b=this.add(a,Fb[a]):!b&&a&&(b=this.o[a.slice(0,2)]);return b||!1===c?b:this.current},getAll:function(){return this.o},set:function(a){var b=this.get(a,!1);if(!b)throw new TypeError("Invalid Locale: "+
a);return this.current=b},add:function(a,c){c?c.code=a:(c=a,a=c.code);var b=c.compiledFormats?c:yb(c);this.o[a]=b;this.current||(this.current=b);return b},remove:function(a){this.current.code===a&&(this.current=this.get("en"));return delete this.o[a]}};X=yb(Db);v=new a(X)})();(function(){function a(a,b,c){b&&E(b.split(" "),function(b){a[b]=c})}function b(a){return function(b,c){return a(b,c).toLowerCase()}}function c(a){return function(b,c){var d=a(b,c);return d+v.get(c).O(d)}}function d(a,b){return function(c,
d){return wa(a(c,d),b)}}function e(a){return function(b,c){return a(b,c)%100}}function f(a){return function(b,c){return Aa(a,b,c)}}function h(c,d){function e(a,b){return c.get(a,b,d)}a(C,c.b+d,e);c.i&&(C[c.i+d]=b(e))}function l(a){return function(b,c){var d=v.get(c);return Aa(d[a],b,c)}}C={};pa={};E(xc,function(g){var l=g.get,m;g.i&&(C[g.i]=b(l));g.l&&(C[g.l]=c(l,g));g.c&&(C[g.c]=d(l,g.c.length));g.u&&(C[g.u]=d(e(l),2));g.A&&(pa[g.A]=d(e(l),2));g.f&&(m=d(l,g.f));g.alias&&(l=f(g.alias));if(g.C)for(var n=
1;5>=n;n++)h(g,n);a(C,g.b,l);a(pa,g.a,m||l)});w(tb,function(b,c){a(C,c,f(b))});Ha(F,"short medium long full",function(b,c){var d=l(c);a(C,c,d);b[c]=d});a(C,"time",l("time"));a(C,"stamp",l("stamp"))})();(function(){Aa=bc(function(a,b,c){return n(C,b)(a,c)},function(a,b,c){return n(pa,b)(a,c)},function(a,b){return x(C,a)||x(pa,b)})})();(function(){Ha(F,U,function(a,b,c){var d=b.name,e=d.charAt(0).toUpperCase()+d.slice(1);4<c&&E(["Last","This","Next"],function(b){a["is"+b+e]=function(a,c){return vb(a,
b+" "+d,0,c,{locale:"en"})}});3<c&&(a["beginningOf"+e]=function(a,b){return na(a,c,b)},a["endOf"+e]=function(a,b){return ya(a,c,b)});a["add"+e+"s"]=function(a,b,c){return la(a,d,b,c)};a[d+"sAgo"]=a[d+"sUntil"]=function(a,c,d){return za(oa(a,c,d,!0).date,a,b)};a[d+"sSince"]=a[d+"sFromNow"]=function(a,c,d){return za(a,oa(a,c,d,!0).date,b)}})})();(function(){Ha(F,"Today Yesterday Tomorrow Weekday Weekend Future Past".split(" ").concat(X.weekdays.slice(0,7)).concat(X.months.slice(0,12)),function(a,b){a["is"+
b]=function(a){return ub(a,b)}})})();(function(a,b){a.prototype.constructor=function(){return b.apply(this,arguments)}})(F,Y);Ia(sc,{remove:function(a,b){for(var c=db(b),d=0;d<a.length;)c(a[d],d,a)?a.splice(d,1):d++;return a}});var zc=/(\d+)?\s*(year|month|week|day|hour|minute|second|millisecond)s?/i,Ac={Hours:36E5,Minutes:6E4,Seconds:1E3,Milliseconds:1},Bc=/(?:from)?\s*(.+)\s+(?:to|until)\s+(.+)$/i,Cc=/(.+)\s*for\s*((?:\d+)?\s*(?:year|month|week|day|hour|minute|second|millisecond))s?/i,Dc=/(?:for)?\s*((?:\d+)?\s*(?:year|month|week|day|hour|minute|second|millisecond))s?\s*(?:starting)?\s(?:at\s)?(.+)/i;
Bb(F,{range:function(a,b){if(1===arguments.length&&K(a)){var c;if(F.get&&(c=a.match(Bc))){var d=ha(c[1].replace("from","at"));var e=F.get(d,c[2]);d=new Va(d,e)}else{if(c=a.match(Dc)){var f=c[1];d=c[2]}if(c=a.match(Cc))d=c[1],f=c[2];d&&f?(d=ha(d),c=f,Q(c)?f=[c,"Milliseconds"]:(f=c.match(zc),c=+f[1]||1,f=f[2].toLowerCase(),f=f.charAt(0).toUpperCase()+f.slice(1),f.match(/hour|minute|second/i)?f+="s":"Year"===f?f="FullYear":"Week"===f?(f="Date",c*=7):"Day"===f&&(f="Date"),f=[c,f]),c=f[0],f=f[1],(e=Ac[f])?
e=new Date(d.getTime()+c*e):(e=new Date(d),ca(e,f,A(d,f)+c))):d=a;d=new Va(ha(d),ha(e))}}else d=new Va(ha(a),ha(b));return d}})}).call(this);

Sugar.extend();